T: 0.04 # total time in terms of one year
fs: 0.05 # samping frequency
Tc: [0.001, 0.0036] # chirp time, fraction of one year
ThetaS: [-1, 1] # sky location arccos uniform [-1,1]
PhiS: [0, 6.283185307179586] # sky location uniform [0, 2pi]
Phic: [0, 6.283185307179586] # chirp phase uniform [0, 2pi]
Iota: [-1, 1] # inclination arccos uniform [-1,1]
Psi: [0, 6.283185307179586] # polarization uniform [0,2pi]
Z: 10 # red shift
SNR: [50, 100, 200] # signal to noise ratio
M1sun: [1000000, 10000000] # M1 in solar mass log-uniform [1e6, 1e7]
M2sun: [1000000, 10000000] # M2 in solar mass log-uniform [1e6, 1e7]
